export const products = [
  {
    id: 1,
    name: "Classic Chocolate Chip",
    price: 3.99,
    originalPrice: 4.99,
    description: "Our signature recipe with premium chocolate chips and a hint of vanilla",
    image: "/placeholder.svg?height=400&width=400",
    category: "Classic",
    inStock: true,
    rating: 4.8,
    reviews: 124,
    type: "regular",
  },
  {
    id: 2,
    name: "Double Chocolate Fudge",
    price: 4.29,
    description: "Rich chocolate cookie loaded with chocolate chunks and fudge pieces",
    image: "/placeholder.svg?height=400&width=400",
    category: "Premium",
    inStock: true,
    rating: 4.9,
    reviews: 89,
    type: "regular",
  },
  {
    id: 3,
    name: "White Chocolate Macadamia",
    price: 4.49,
    description: "Buttery cookie with white chocolate chips and roasted macadamia nuts",
    image: "/placeholder.svg?height=400&width=400",
    category: "Premium",
    inStock: true,
    rating: 4.7,
    reviews: 156,
    type: "regular",
  },
  {
    id: 4,
    name: "Birthday Cake Cookie",
    price: 4.99,
    description: "Funfetti cookie with vanilla frosting and colorful sprinkles",
    image: "/placeholder.svg?height=400&width=400",
    category: "Specialty",
    inStock: true,
    rating: 4.6,
    reviews: 203,
    type: "regular",
  },
  {
    id: 5,
    name: "Oatmeal Raisin",
    price: 3.79,
    originalPrice: 4.29,
    description: "Traditional oatmeal cookie with plump raisins and warm cinnamon",
    image: "/placeholder.svg?height=400&width=400",
    category: "Classic",
    inStock: true,
    rating: 4.5,
    reviews: 78,
    type: "regular",
  },
  {
    id: 6,
    name: "Peanut Butter Crunch",
    price: 4.19,
    description: "Creamy peanut butter cookie with crunchy peanut pieces",
    image: "/placeholder.svg?height=400&width=400",
    category: "Premium",
    inStock: false,
    rating: 4.8,
    reviews: 167,
    type: "regular",
  },
  {
    id: 7,
    name: "Snickerdoodle",
    price: 3.89,
    description: "Soft cinnamon sugar cookie rolled in our special spice blend",
    image: "/placeholder.svg?height=400&width=400",
    category: "Classic",
    inStock: true,
    rating: 4.7,
    reviews: 92,
    type: "regular",
  },
  {
    id: 8,
    name: "Red Velvet Cream Cheese",
    price: 5.29,
    description: "Rich red velvet cookie topped with cream cheese frosting",
    image: "/placeholder.svg?height=400&width=400",
    category: "Specialty",
    inStock: true,
    rating: 4.9,
    reviews: 134,
    type: "regular",
  },
  // Custom Bundle products
  {
    id: 101,
    name: "3 Cookie Bundle",
    price: 0, // Price will be calculated based on selection
    description: "Create your perfect mix of 3 mini cookies from our available flavors",
    image: "/placeholder.svg?height=400&width=400",
    category: "Bundles",
    inStock: true,
    rating: 4.8,
    reviews: 45,
    type: "bundle",
    bundleSize: 3,
  },
  {
    id: 102,
    name: "6 Cookie Bundle",
    price: 0, // Price will be calculated based on selection
    description: "Create your perfect mix of 6 mini cookies from our available flavors",
    image: "/placeholder.svg?height=400&width=400",
    category: "Bundles",
    inStock: true,
    rating: 4.9,
    reviews: 67,
    type: "bundle",
    bundleSize: 6,
  },
  {
    id: 103,
    name: "9 Cookie Bundle",
    price: 0, // Price will be calculated based on selection
    description: "Create your perfect mix of 9 mini cookies from our available flavors",
    image: "/placeholder.svg?height=400&width=400",
    category: "Bundles",
    inStock: true,
    rating: 4.8,
    reviews: 34,
    type: "bundle",
    bundleSize: 9,
  },
  {
    id: 104,
    name: "12 Cookie Bundle",
    price: 0, // Price will be calculated based on selection
    description: "Create your perfect mix of 12 mini cookies from our available flavors",
    image: "/placeholder.svg?height=400&width=400",
    category: "Bundles",
    inStock: true,
    rating: 4.9,
    reviews: 89,
    type: "bundle",
    bundleSize: 12,
  },
]

// Available mini cookies for bundles
export const miniCookies = [
  {
    id: 201,
    name: "Mini Chocolate Chip",
    price: 1.25,
    description: "Bite-sized version of our classic chocolate chip cookie",
    image: "/placeholder.svg?height=300&width=300",
    category: "Mini",
    inStock: true,
  },
  {
    id: 202,
    name: "Mini Sugar Cookie",
    price: 1.15,
    description: "Sweet and simple mini sugar cookie with a soft texture",
    image: "/placeholder.svg?height=300&width=300",
    category: "Mini",
    inStock: true,
  },
  {
    id: 203,
    name: "Mini Oatmeal",
    price: 1.25,
    description: "Mini oatmeal cookie with a hint of cinnamon",
    image: "/placeholder.svg?height=300&width=300",
    category: "Mini",
    inStock: true,
  },
]

export const categories = [
  {
    id: 1,
    name: "Classic Cookies",
    count: 12,
    slug: "classic",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 2,
    name: "Specialty Flavors",
    count: 8,
    slug: "specialty",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 3,
    name: "Gift Boxes",
    count: 6,
    slug: "gift-boxes",
    image: "/placeholder.svg?height=400&width=600",
  },
  {
    id: 4,
    name: "Mini Cookie Bundles",
    count: 4,
    slug: "bundles",
    image: "/placeholder.svg?height=400&width=600",
  },
]

export const bundles = [
  { size: 3, discount: 0.1, name: "Triple Pack", emoji: "🍪" },
  { size: 6, discount: 0.15, name: "Half Dozen", emoji: "🎁" },
  { size: 12, discount: 0.2, name: "Dozen Box", emoji: "📦" },
]
